#!/bin/bash

# Clear the package cache
echo "Clearing package cache..."
sudo pacman -Scc --noconfirm

# Check for and remove unused orphaned packages
orphans=$(pacman -Qtdq)
if [ -n "$orphans" ]; then
    echo "Removing unused dependencies..."
    sudo pacman -Rns "$orphans"
else
    echo "No orphaned packages to remove."
fi

# Clear the user's cache directory
echo "Clearing user cache..."
rm -rf "$HOME/.cache/*"

# Run rmlint to find and flag unnecessary files
echo "Running rmlint..."
rmlint "$HOME" > "$HOME/rmlint.log" 2>&1

# Execute the script generated by rmlint
if [ -f "$HOME/rmlint.sh" ]; then
    echo "Executing rmlint.sh to remove flagged files..."
    sh "$HOME/rmlint.sh" -d
else
    echo "rmlint.sh not found. Skipping file removal."
fi

# Delete rmlint.json if it exists
if [ -f "$HOME/rmlint.json" ]; then
    echo "Deleting rmlint.json..."
    rm "$HOME/rmlint.json"
else
    echo "No rmlint.json found to delete."
fi

# Vacuum the system journal to limit its size
echo "Vacuuming system journal to 50M..."
sudo journalctl --vacuum-size=50M > /dev/null 2>&1

# Empty the trash
echo "Emptying trash..."
rm -rf $HOME/.local/share/Trash/*

echo "🧹 System cleanup completed! 🎉"

